version: '3.1'

services:
  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - ./data/redis_data:/data
    ports:
      - "6379:6379"
    logging:
      driver: none

  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - ./data/db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=paimon
    logging:
      driver: none
